spring:
  datasource:
    url: jdbc:h2:file:./data/devdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

app:
  jwt:
    secret: "change-this-in-prod-very-long-secret"
    expiration-minutes: 60

# Для хранения медиафайлов (Задание 3)
storage:
  media-dir: ./media
  max-size-mb: 5
